### ISSUE TITLE
CHIRIMEN章の内容

### ISSUE THREAD

**Issue by sizuhiko** [gurezo/chirimen.org#11]
LED、ブレッドボード、JavaScript あたりの内容はなくても良いのかなぁ？という気持ち
実際、ほとんど外部リンクだし

CHIRIMEN について、GPIO, I2C, IoT あたりだけで良さそう

**Comment by sizuhiko** [comment]
GPIO の micro:Bit の内容は削除して良さそう

**Comment by gurezo** [comment]
上記の情報を書籍先頭に移動予定

**Comment by gurezo** [comment]
#14

**Comment by gurezo** [comment]
> LED、ブレッドボード、JavaScript あたりの内容はなくても良いのかなぁ？という気持ち 実際、ほとんど外部リンクだし
> 
> CHIRIMEN について、GPIO, I2C, IoT あたりだけで良さそう

微妙と思いつつ #17 で、整理してみました。
不要であれば、削除するスタンスです。

**Comment by gurezo** [comment]
#14 merged

**Comment by gurezo** [comment]
#14 merged
