### ISSUE TITLE
外部リンクだけの箇条書きを、本文中出現箇所でリンクに変更する

### ISSUE THREAD

**Issue by sizuhiko** [gurezo/chirimen.org#5]
P.7 ステップ1のNoteにある、 CLIとは みたいに、外部リンクだけの箇条書きは最初の1行目のところの出現箇所でリンクする

**Comment by sizuhiko** [comment]
リンク済みなので不要と思われる箇所

- P.4 準備 「講習会では書き込み済みmicroSDが配布されると思いますが... 」 は、1つ上のインデントでリンク済み
- P.8 Note の CLI, シェルとコマンドプロンプト
- P.12 実行する の node
- P.14 シングルボードコンピュータ
- P.22 センサーの極性に注意
- P.23 i2c detect
- P.25 CodeSandbox
- P.28 予備知識
- P.32 LED
- P.33 ブレッドボード、抵抗値の読み方
- P.36 JavaScript
- P.39 GPIO micro:bit は不要
- P.40 プルアップ/ダウン
- P.43 ポーリング
- P.47 I2C参考
- P.49 i2c detect
- P.50 i2c detect
- P.55 データシート/ドライバライブラリ
- P.56 IoT
- P.57 詳しくはこちら
-

**Comment by sizuhiko** [comment]
LED, ブレッドボード、抵抗値の読み方, JavaScript については #11 の内容で相談

**Comment by gurezo** [comment]
merged

**Comment by gurezo** [comment]
[CHIRIMEN Raspberry Pi Zero W チュートリアル.pdf](https://github.com/gurezo/chirimen.org/files/12837858/CHIRIMEN.Raspberry.Pi.Zero.W.pdf)

- P.5 CHIRIMEN の動作環境
  - [ ] ブラウザを使わずNode.js からも使えます。
  - [ ] JavaScript 初学者向け資料集
- P.7 Raspberry Pi について
  - [ ] フルセットのブラウザが内蔵されたデバイスを作りたい場合はCHIRIMEN Raspberry Pi版が使⽤できます
  - [ ] インターネットを経由してPCやスマホのブラウザから遠隔操作するシステムは このPi ZeroW版でつくれます。IoTの章まで進めましょう。=> md 参照をhtml 参照に変える
- P.14 Hello Real World（Lチカを実⾏する）
  - [ ] LED の説明
  - [ ] ブレッドボードの使い方
  - [ ] 抵抗値の読み方
 - P.17 GPIO を試す
  - [ ] GPIOとは？ => md 参照をhtml 参照に変える
  - [ ] MOSFETを使った大電力制御
  - [ ] JavaScript Module
  - [ ] GPIOポートの初期化処理
  - [ ] GPIOPortの出力処理
 - P.18 GPIO 入力
  - [ ] JavaScript Module
  - [ ] GPIOポートの初期化処理
  - [ ] GPIOPortの出力処理
 - P.19 GPIO 入力（ポーリング）
  - [ ] JavaScript Module
  - [ ] GPIOポートの初期化処理
  - [ ] 単純入力＋ポーリングによる入力処理
 - P.20 I2Cデバイスを試す
  - [ ] I2Cとは？ => md 参照をhtml 参照に変える
  - [ ] SHT30/SHT31について
 - P.21 I2Cデバイスを試す
  - [ ] I2Cとは？ => md 参照をhtml 参照に変える
  - [ ] JavaScript Module
  - [ ] I2C 温湿度センサー (SHT30, SHT31)の初期化と使用

**Comment by gurezo** [comment]
#17 merged

**Comment by gurezo** [comment]
#19 merge したので、close
